include $(TOPDIR)/rules.mk

PKG_NAME:=libibm-iotp
PKG_RELEASE:=1
PKG_VERSION:=1.0.0
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/ibm-watson-iot/iot-c
PKG_SOURCE_VERSION:=f921dce616af815da2236954c608a2f377c928c5

include $(INCLUDE_DIR)/package.mk

define Package/libibm-iotp
	CATEGORY:=Libraries
	TITLE:=libibm-iotp
endef

define Package/libibm-iotp/description
	IBM Watson IoT Platform (IoTP) C Client SDK
endef

define Build/InstallDev

endef

define Package/libibm-iotp/InstallDev

endef

$(eval $(call BuildPackage,libibm-iotp))